# SPDX-FileCopyrightText: Copyright (c) 2024, Contributors
# SPDX-License-Identifier: Apache-2.0
"""
solver.py — Darcy flow / variable-conductivity heat equation solver.

Physics
-------
    -∇·(a(x)∇u) = f    on Ω = [0,1]²
    u = 0               on ∂Ω  (Dirichlet)

This is mathematically identical to steady-state heat conduction with a
spatially-varying thermal conductivity k(x) = a(x):

    -∇·(k(x)∇T) = Q

The training dataset (128×128) was generated by a high-fidelity finite-element
solver (FEniCS) — generating 10,000+ samples took hours on a workstation.
Data source: Zenodo record 12784353 (~356 MB download, cached after first run).

This script provides:
  - load_darcy_data()  : download & load the Zenodo dataset via neuraloperator
  - solve_darcy_fd()   : reference FD solver using scipy sparse (for comparison)

Usage
-----
python solver.py   # downloads data, benchmarks one solve
"""

import sys
import time
from pathlib import Path
from typing import Tuple

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

DATA_ROOT = Path(__file__).parent / "data" / "darcy"


# ─── Dataset loading ─────────────────────────────────────────────────────────

def load_darcy_data(
    n_train: int = 1000,
    n_test: int = 200,
    resolution: int = 128,
    subsample: int = 1,
    data_root: Path = DATA_ROOT,
) -> Tuple:
    """Download (once) and return Darcy flow training and test tensors.

    Parameters
    ----------
    n_train : int
    n_test  : int
    resolution : int
        Native resolution of the dataset.  Must be one of [16, 32, 64, 128, 421].
    subsample : int
        Stride for spatial subsampling (e.g. subsample=2 → 64×64 grid).
    data_root : Path

    Returns
    -------
    a_train, u_train : np.ndarray, shape (n_train, 1, H', W')
    a_test,  u_test  : np.ndarray, shape (n_test,  1, H', W')
    """
    from neuralop.data.datasets.darcy import DarcyDataset
    import torch

    data_root.mkdir(parents=True, exist_ok=True)
    ds = DarcyDataset(
        root_dir=data_root,
        n_train=n_train,
        n_tests=[n_test],
        batch_size=n_train,
        test_batch_sizes=[n_test],
        train_resolution=resolution,
        test_resolutions=[resolution],
        encode_input=False,
        encode_output=False,
        download=True,
    )

    from torch.utils.data import DataLoader

    def _extract(db, n):
        loader = DataLoader(db, batch_size=n, shuffle=False, num_workers=0)
        batch  = next(iter(loader))
        a = batch["x"].numpy()   # (n, 1, H, W)  or (n, H, W)
        u = batch["y"].numpy()
        if a.ndim == 3:
            a = a[:, None]
        if u.ndim == 3:
            u = u[:, None]
        if subsample > 1:
            a = a[:, :, ::subsample, ::subsample]
            u = u[:, :, ::subsample, ::subsample]
        return a.astype(np.float32), u.astype(np.float32)

    a_train, u_train = _extract(ds.train_db,          n_train)
    a_test,  u_test  = _extract(ds.test_dbs[resolution], n_test)
    return a_train, u_train, a_test, u_test


# ─── Reference FD solver ─────────────────────────────────────────────────────

def _assemble_darcy_matrix(a: np.ndarray) -> sp.csr_matrix:
    """Build the (H-2)(W-2) × (H-2)(W-2) sparse stiffness matrix for

        -div(a(x) grad u) = f    with u = 0 on boundary

    using a 5-point cell-centred FD scheme with arithmetic-mean interface
    conductivities.  Fully vectorised — no Python loops.
    """
    H, W = a.shape
    h  = 1.0 / (H - 1)
    ni = H - 2
    nj = W - 2
    n  = ni * nj

    # Interior slice of a: a_int[i,j] = a[i+1, j+1]
    a_int = a[1:-1, 1:-1]                    # (ni, nj)

    # Interface conductivities (arithmetic mean)
    ae  = 0.5 * (a_int + a[1:-1, 2:  ])     # east
    aw  = 0.5 * (a_int + a[1:-1,  :-2])     # west
    an  = 0.5 * (a_int + a[2:,   1:-1])     # north
    as_ = 0.5 * (a_int + a[ :-2, 1:-1])     # south

    inv_h2 = 1.0 / h**2
    idx = np.arange(n).reshape(ni, nj)      # linear index of interior nodes

    # ── Diagonal ──────────────────────────────────────────────────────────────
    d_rows = idx.ravel()
    d_cols = idx.ravel()
    d_vals = (ae + aw + an + as_).ravel() * inv_h2

    # ── East (j+1) ────────────────────────────────────────────────────────────
    e_rows = idx[:, :-1].ravel()
    e_cols = idx[:, 1: ].ravel()
    e_vals = -ae[:, :-1].ravel() * inv_h2

    # ── West (j-1) ────────────────────────────────────────────────────────────
    w_rows = idx[:, 1: ].ravel()
    w_cols = idx[:, :-1].ravel()
    w_vals = -aw[:, 1: ].ravel() * inv_h2

    # ── North (i+1) ───────────────────────────────────────────────────────────
    n_rows = idx[:-1, :].ravel()
    n_cols = idx[1:,  :].ravel()
    n_vals = -an[:-1, :].ravel() * inv_h2

    # ── South (i-1) ───────────────────────────────────────────────────────────
    s_rows = idx[1:,  :].ravel()
    s_cols = idx[:-1, :].ravel()
    s_vals = -as_[1:, :].ravel() * inv_h2

    rows = np.concatenate([d_rows, e_rows, w_rows, n_rows, s_rows])
    cols = np.concatenate([d_cols, e_cols, w_cols, n_cols, s_cols])
    vals = np.concatenate([d_vals, e_vals, w_vals, n_vals, s_vals])

    return sp.csr_matrix((vals, (rows, cols)), shape=(n, n))


def solve_darcy_fd(
    a_field: np.ndarray,
    f: float = 1.0,
    a_lo: float = 3.0,
    a_hi: float = 12.0,
) -> Tuple[np.ndarray, float]:
    """Solve -div(a(x) grad u) = f with Dirichlet u=0 on boundary.

    Parameters
    ----------
    a_field : ndarray, shape (H, W)
        Permeability field.  If values are in [0, 1] (as stored in the Zenodo
        dataset), they are mapped to physical conductivities via
        ``a_physical = a_lo + (a_hi - a_lo) * a_field`` so that all interface
        conductivities remain strictly positive.
    f : float
        Uniform forcing (right-hand side).
    a_lo, a_hi : float
        Physical conductivity range; default {3, 12} follows the original
        FNO paper (Li et al. 2020).

    Returns
    -------
    u : ndarray, shape (H, W)
    elapsed : float  [seconds]
    """
    H, W = a_field.shape
    # Map normalised [0,1] field → physical conductivities [a_lo, a_hi]
    a_phys = (a_lo + (a_hi - a_lo) * a_field).astype(np.float64)

    t0 = time.perf_counter()
    A = _assemble_darcy_matrix(a_phys)
    rhs = np.full((H - 2) * (W - 2), f)
    u_int = spla.spsolve(A, rhs)
    elapsed = time.perf_counter() - t0

    u = np.zeros((H, W))
    u[1:-1, 1:-1] = u_int.reshape(H - 2, W - 2)
    return u, elapsed


# ─── CLI smoke-test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    import matplotlib.pyplot as plt

    print("Loading one test sample …")
    a_train, u_train, a_test, u_test = load_darcy_data(n_train=5, n_test=5, resolution=128)
    print(f"  a shape: {a_train.shape}   range [{a_train.min():.2f}, {a_train.max():.2f}]")
    print(f"  u shape: {u_train.shape}   range [{u_train.min():.4f}, {u_train.max():.4f}]")

    a0 = a_train[0, 0]     # (128, 128)
    u_ref = u_train[0, 0]

    print(f"\nSolving at {a0.shape[0]}×{a0.shape[1]} with scipy sparse …")
    u_fd, t = solve_darcy_fd(a0)
    print(f"  elapsed: {t:.3f}s")

    # Note: FEM ground truth uses a different forcing scale; this comparison
    # is primarily to verify the FD solver runs without error.
    print(f"  FD u range: [{u_fd.min():.4f}, {u_fd.max():.4f}]  (FEM ref: [{u_ref.min():.4f}, {u_ref.max():.4f}])")

    fig, axes = plt.subplots(1, 3, figsize=(13, 4))
    for ax, data, title, cmap in zip(
        axes,
        [a0, u_ref, u_fd],
        ["Conductivity a(x)", "FEM solution (ground truth)", f"FD solver  ({t:.2f}s)"],
        ["hot", "viridis", "viridis"],
    ):
        im = ax.imshow(data, cmap=cmap, origin="lower", interpolation="bilinear")
        ax.set_title(title, fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    plt.suptitle("Darcy Flow / Variable-Conductivity Heat Equation", fontweight="bold")
    plt.tight_layout()
    plt.savefig("solver_demo.png", dpi=130)
    print("Saved solver_demo.png")
