# SPDX-FileCopyrightText: Copyright (c) 2024, Contributors
# SPDX-License-Identifier: Apache-2.0
"""
train.py — Train an FNO surrogate on the Darcy flow / variable-conductivity
heat equation dataset.

Dataset
-------
1000 training + 200 test samples at 421×421 resolution, generated by a
high-fidelity FEM solver (FEniCS).  The full dataset is downloaded once from
Zenodo (~1.5 GB) and cached locally.

The 421×421 fields are subsampled to 64×64 for FNO training, following the
original FNO paper (Li et al. 2020).  A fully-trained model achieves
rel-L2 < 1% on held-out test samples.

Usage
-----
# GPU (recommended)
python train.py --device cuda

# CPU-only (slower, fewer epochs)
python train.py --device cpu --n_train 200 --epochs 20

# Quick sanity-check (60 s on GPU)
python train.py --device cuda --n_train 100 --epochs 5
"""

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from solaris.models.fno import FNO
from solaris.metrics import relative_l2_error
from solaris.utils import get_logger, save_checkpoint
from solver import load_darcy_data


# ─── Training loop ───────────────────────────────────────────────────────────

def train(args):
    log = get_logger("train")
    device = torch.device(
        args.device if (torch.cuda.is_available() or args.device == "cpu") else "cpu"
    )
    log.info(f"Device: {device}")
    if device.type == "cuda":
        log.info(f"GPU: {torch.cuda.get_device_name(0)}")

    # ── Load dataset ──
    log.info(
        f"Loading Darcy {args.resolution}×{args.resolution} dataset "
        f"(n_train={args.n_train}, n_test={args.n_val}, subsample={args.subsample}) …"
    )
    a_train, u_train, a_val, u_val = load_darcy_data(
        n_train=args.n_train,
        n_test=args.n_val,
        resolution=args.resolution,
        subsample=args.subsample,
    )

    H, W = a_train.shape[-2], a_train.shape[-1]
    log.info(f"Effective resolution after subsampling: {H}×{W}")
    log.info(f"  a range [{a_train.min():.3f}, {a_train.max():.3f}]")
    log.info(f"  u range [{u_train.min():.5f}, {u_train.max():.5f}]")

    # ── Normalise ──
    a_mean, a_std = a_train.mean(), a_train.std() + 1e-8
    u_mean, u_std = u_train.mean(), u_train.std() + 1e-8

    a_train_n = (a_train - a_mean) / a_std
    u_train_n = (u_train - u_mean) / u_std
    a_val_n   = (a_val   - a_mean) / a_std
    u_val_n   = (u_val   - u_mean) / u_std

    ckpt_dir = Path(args.checkpoint_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    np.savez(
        ckpt_dir / "norm_stats.npz",
        a_mean=a_mean, a_std=a_std,
        u_mean=u_mean, u_std=u_std,
    )

    # ── DataLoaders ──
    def to_loader(a, u, shuffle):
        ds = TensorDataset(
            torch.as_tensor(a, dtype=torch.float32),
            torch.as_tensor(u, dtype=torch.float32),
        )
        return DataLoader(
            ds, batch_size=args.batch_size, shuffle=shuffle,
            pin_memory=(device.type == "cuda"),
        )

    train_loader = to_loader(a_train_n, u_train_n, shuffle=True)
    val_loader   = to_loader(a_val_n,   u_val_n,   shuffle=False)

    # ── Model ──
    model = FNO(
        in_channels=1, out_channels=1,
        hidden_channels=args.hidden,
        n_layers=args.n_layers,
        modes=args.modes,
        dim=2,
    ).to(device)
    log.info(f"FNO parameters: {model.num_parameters():,}")

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    loss_fn   = nn.MSELoss()

    best_val = float("inf")
    log.info("Starting training …")

    for epoch in range(1, args.epochs + 1):
        model.train()
        tr_loss = 0.0
        for a_b, u_b in train_loader:
            a_b, u_b = a_b.to(device), u_b.to(device)
            optimizer.zero_grad()
            pred = model(a_b)
            loss = loss_fn(pred, u_b)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tr_loss += loss.item() * len(a_b)
        tr_loss /= len(train_loader.dataset)
        scheduler.step()

        model.eval()
        val_loss, val_l2 = 0.0, 0.0
        with torch.no_grad():
            for a_b, u_b in val_loader:
                a_b, u_b = a_b.to(device), u_b.to(device)
                pred = model(a_b)
                val_loss += loss_fn(pred, u_b).item() * len(a_b)
                val_l2   += relative_l2_error(pred, u_b).item() * len(a_b)
        val_loss /= len(val_loader.dataset)
        val_l2   /= len(val_loader.dataset)

        log.info(
            f"Epoch {epoch:3d}/{args.epochs} "
            f"| train={tr_loss:.3e} | val={val_loss:.3e} "
            f"| rel-L2={val_l2:.4f} | lr={scheduler.get_last_lr()[0]:.2e}"
        )

        if val_loss < best_val:
            best_val = val_loss
            save_checkpoint(
                ckpt_dir / "best_fno.pt",
                model, optimizer, scheduler, epoch, val_loss,
                extra={
                    "hidden_channels": args.hidden,
                    "n_layers":        args.n_layers,
                    "modes":           args.modes,
                    "subsample":       args.subsample,
                    "resolution":      args.resolution,
                },
            )

    log.info(f"Training complete. Best val loss: {best_val:.4e}")
    log.info(f"Checkpoint → {ckpt_dir}/best_fno.pt")


# ─── CLI ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--device",         default="cuda")
    p.add_argument("--resolution",     type=int,   default=128,
                   help="Dataset resolution (128 default; 421 for full-res)")
    p.add_argument("--n_train",        type=int,   default=1000)
    p.add_argument("--n_val",          type=int,   default=200)
    p.add_argument("--subsample",      type=int,   default=1,
                   help="Spatial subsampling stride (1 = no subsample)")
    p.add_argument("--epochs",         type=int,   default=100)
    p.add_argument("--batch_size",     type=int,   default=16)
    p.add_argument("--lr",             type=float, default=1e-3)
    p.add_argument("--hidden",         type=int,   default=64)
    p.add_argument("--modes",          type=int,   default=12)
    p.add_argument("--n_layers",       type=int,   default=4)
    p.add_argument("--checkpoint_dir", default="checkpoints")
    train(p.parse_args())
