# SPDX-FileCopyrightText: Copyright (c) 2024, Contributors
# SPDX-License-Identifier: Apache-2.0
"""
train.py — Train an FNO surrogate on the chip thermal dataset.

Dataset
-------
1 000 training + 200 test samples at 128×128 resolution, generated by the
scipy sparse FD solver in solver.py.  The dataset is generated once and
cached to data/chip_thermal_dataset.npz.

The FNO learns to map power-density Q(x,y) → temperature T(x,y).  After
training on a GPU the model achieves rel-L2 < 1 % on held-out samples.

Usage
-----
# GPU (recommended)
python train.py --device cuda

# CPU-only
python train.py --device cpu --n_train 200 --epochs 20

# Quick sanity-check
python train.py --device cuda --n_train 100 --epochs 5
"""

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from solaris.models.fno import FNO
from solaris.metrics import relative_l2_error
from solaris.utils import get_logger, save_checkpoint
from solver import generate_dataset


# ─── Training loop ───────────────────────────────────────────────────────────

def train(args):
    log = get_logger("train")
    device = torch.device(
        args.device if (torch.cuda.is_available() or args.device == "cpu") else "cpu"
    )
    log.info(f"Device: {device}")
    if device.type == "cuda":
        log.info(f"GPU: {torch.cuda.get_device_name(0)}")

    # ── Generate / load dataset ──
    data_path = generate_dataset(
        n_train=args.n_train,
        n_test=args.n_val,
        H=args.resolution,
        W=args.resolution,
    )
    log.info(f"Loading dataset from {data_path} …")
    d = np.load(data_path)
    Q_train = d["Q_train"]   # (n_train, H, W) float32
    T_train = d["T_train"]
    Q_val   = d["Q_test"]
    T_val   = d["T_test"]

    H, W = Q_train.shape[1], Q_train.shape[2]
    log.info(f"Resolution: {H}×{W}  |  train: {len(Q_train)}  |  val: {len(Q_val)}")
    log.info(f"  Q range [{Q_train.min():.0f}, {Q_train.max():.0f}]")
    log.info(f"  T range [{T_train.min():.1f} °C, {T_train.max():.1f} °C]")

    # ── Normalise ──
    Q_mean = float(Q_train.mean());  Q_std = float(Q_train.std()) + 1e-8
    T_mean = float(T_train.mean());  T_std = float(T_train.std()) + 1e-8

    Q_tr_n = (Q_train - Q_mean) / Q_std
    T_tr_n = (T_train - T_mean) / T_std
    Q_va_n = (Q_val   - Q_mean) / Q_std
    T_va_n = (T_val   - T_mean) / T_std

    ckpt_dir = Path(args.checkpoint_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    np.savez(
        ckpt_dir / "norm_stats.npz",
        Q_mean=Q_mean, Q_std=Q_std,
        T_mean=T_mean, T_std=T_std,
    )

    # ── DataLoaders ──
    def to_loader(Q, T, shuffle):
        ds = TensorDataset(
            torch.as_tensor(Q[:, None], dtype=torch.float32),   # (N, 1, H, W)
            torch.as_tensor(T[:, None], dtype=torch.float32),
        )
        return DataLoader(
            ds, batch_size=args.batch_size, shuffle=shuffle,
            pin_memory=(device.type == "cuda"),
        )

    train_loader = to_loader(Q_tr_n, T_tr_n, shuffle=True)
    val_loader   = to_loader(Q_va_n, T_va_n, shuffle=False)

    # ── Model ──
    model = FNO(
        in_channels=1, out_channels=1,
        hidden_channels=args.hidden,
        n_layers=args.n_layers,
        modes=args.modes,
        dim=2,
    ).to(device)
    log.info(f"FNO parameters: {model.num_parameters():,}")

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    loss_fn   = nn.MSELoss()

    best_val = float("inf")
    log.info("Starting training …")

    for epoch in range(1, args.epochs + 1):
        model.train()
        tr_loss = 0.0
        for Q_b, T_b in train_loader:
            Q_b, T_b = Q_b.to(device), T_b.to(device)
            optimizer.zero_grad()
            pred = model(Q_b)
            loss = loss_fn(pred, T_b)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tr_loss += loss.item() * len(Q_b)
        tr_loss /= len(train_loader.dataset)
        scheduler.step()

        model.eval()
        val_loss, val_l2 = 0.0, 0.0
        with torch.no_grad():
            for Q_b, T_b in val_loader:
                Q_b, T_b = Q_b.to(device), T_b.to(device)
                pred = model(Q_b)
                val_loss += loss_fn(pred, T_b).item() * len(Q_b)
                val_l2   += relative_l2_error(pred, T_b).item() * len(Q_b)
        val_loss /= len(val_loader.dataset)
        val_l2   /= len(val_loader.dataset)

        log.info(
            f"Epoch {epoch:3d}/{args.epochs} "
            f"| train={tr_loss:.3e} | val={val_loss:.3e} "
            f"| rel-L2={val_l2:.4f} | lr={scheduler.get_last_lr()[0]:.2e}"
        )

        if val_loss < best_val:
            best_val = val_loss
            save_checkpoint(
                ckpt_dir / "best_fno.pt",
                model, optimizer, scheduler, epoch, val_loss,
                extra={
                    "hidden_channels": args.hidden,
                    "n_layers":        args.n_layers,
                    "modes":           args.modes,
                    "resolution":      args.resolution,
                },
            )

    log.info(f"Training complete. Best val loss: {best_val:.4e}")
    log.info(f"Checkpoint → {ckpt_dir}/best_fno.pt")


# ─── CLI ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--device",         default="cuda")
    p.add_argument("--resolution",     type=int,   default=128)
    p.add_argument("--n_train",        type=int,   default=1000)
    p.add_argument("--n_val",          type=int,   default=200)
    p.add_argument("--epochs",         type=int,   default=200)
    p.add_argument("--batch_size",     type=int,   default=16)
    p.add_argument("--lr",             type=float, default=1e-3)
    p.add_argument("--hidden",         type=int,   default=64)
    p.add_argument("--modes",          type=int,   default=16)
    p.add_argument("--n_layers",       type=int,   default=4)
    p.add_argument("--checkpoint_dir", default="checkpoints")
    train(p.parse_args())
